# Generated by Django 4.1.3 on 2022-12-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carCompany", models.CharField(max_length=15)),
                ("carName", models.CharField(max_length=15)),
                ("manu_Date", models.DateField()),
                ("kilometers", models.IntegerField()),
                ("Fuel_type", models.CharField(max_length=10)),
                ("color", models.CharField(max_length=10)),
                ("first_owner", models.BooleanField()),
                ("expected_price", models.IntegerField()),
                ("car_insurance", models.CharField(max_length=15)),
                ("insurance_type", models.CharField(max_length=15)),
                ("car_registration_no", models.CharField(max_length=10)),
                ("images", models.ImageField(upload_to="Images")),
            ],
        ),
    ]
