# Generated by Django 4.1.3 on 2023-01-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user_details", name="cars_selled",),
    ]
