# Generated by Django 4.1.3 on 2023-01-07 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0004_alter_car_id"),
        ("user", "0002_remove_user_details_cars_selled"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_details",
            name="selled_car",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="seller.car"
            ),
        ),
    ]
