# Generated by Django 4.1.3 on 2023-01-09 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0004_alter_car_id"),
        ("user", "0004_userprofile"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="bio",),
        migrations.AddField(
            model_name="userprofile",
            name="Address",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="contact_number",
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="userprofile", name="dob", field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="selled_car",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="seller.car"
            ),
        ),
    ]
