# Generated by Django 4.1.3 on 2023-01-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_remove_userprofile_bio_userprofile_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
